### ISSUE TITLE
Would you like to contribute this rule to maven-enforcer-plugin?

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [esamson/checksum-enforcer-rule#1]
Hi.

Thank you for implementing such a nice rule as it took only a few seconds to find it and it helped to configure my build more precisely. Would you like to contribute this rule to the original maven-enforcer-plugin distribution? The plugin still seems to have no support for validating checksums, but I think it would be great to have such a nice feature out of box.

What do you think?

**Comment by esamson** [comment]
I'm glad you like it. I have no objections to contributing this -- I just haven't put any thought into the contribution process. I don't even know if the enforcer-plugin guys would be interested.

If you're interested in facilitating, feel free. Otherwise, it provides very little functionality and I think it's useful enough the way it is now. I release to Central anyway so adding to your build is as simple as the example in the README.

Thanks!

**Comment by lyubomyr-shaydariv** [comment]
I've adapted your code and raised a ticket in their JIRA: https://issues.apache.org/jira/browse/MENFORCER-247 -- I hope I'll get some feedback.

Edit:
By the way, during the migration to Apache Commons Codec 1.6 CRC-32 and CRC-32C have been lost as unsupported, but it supports SHA-384 now.

**Comment by lyubomyr-shaydariv** [comment]
Maven Enforcer Plugin [3.0.0](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-enforcer-plugin/3.0.0) is now, 5 years later, finally released. Thanks @esamson !

**Comment by esamson** [comment]
Very cool @lyubomyr-shaydariv ! I guess I should retire this project now. :) Cheers!
